@startuml GridNodeLogic
state "GridNodeLogic State" as Vertex_GridNode_State_GridNodeLogic_State {
  state "Unmarked" as Vertex_GridNode_State_GridNodeLogic_State_Unmarked {
    state "Hover" as Vertex_GridNode_State_GridNodeLogic_State_Hover
    state "UnmarkedDisabled" as Vertex_GridNode_State_GridNodeLogic_State_UnmarkedDisabled
    state "UnmarkedIdle" as Vertex_GridNode_State_GridNodeLogic_State_UnmarkedIdle
    state "Spawning" as Vertex_GridNode_State_GridNodeLogic_State_Spawning
  }
  state "Marked" as Vertex_GridNode_State_GridNodeLogic_State_Marked {
    state "MarkedDisabled" as Vertex_GridNode_State_GridNodeLogic_State_MarkedDisabled
    state "WinningLine" as Vertex_GridNode_State_GridNodeLogic_State_WinningLine
    state "Marking" as Vertex_GridNode_State_GridNodeLogic_State_Marking
    state "MarkedIdle" as Vertex_GridNode_State_GridNodeLogic_State_MarkedIdle
  }
}

Vertex_GridNode_State_GridNodeLogic_State_Hover --> Vertex_GridNode_State_GridNodeLogic_State_UnmarkedIdle : HoverExit
Vertex_GridNode_State_GridNodeLogic_State_Spawning --> Vertex_GridNode_State_GridNodeLogic_State_UnmarkedIdle : Spawned
Vertex_GridNode_State_GridNodeLogic_State_UnmarkedIdle --> Vertex_GridNode_State_GridNodeLogic_State_Hover : HoverEnter

Vertex_GridNode_State_GridNodeLogic_State_Hover : OnEnter → HoverEntered
Vertex_GridNode_State_GridNodeLogic_State_Hover : OnExit → HoverExited
Vertex_GridNode_State_GridNodeLogic_State_Spawning : OnEnter → SpawnStarted
Vertex_GridNode_State_GridNodeLogic_State_Spawning : OnExit → SpawnComplete

[*] --> Vertex_GridNode_State_GridNodeLogic_State_Spawning
@enduml